# Generated by Django 5.0.1 on 2024-01-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.IntegerField()),
                ('subject_code', models.CharField(max_length=50)),
                ('exam_date', models.DateField()),
                ('total_questions', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FacultyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
                ('department', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=250)),
                ('question_text', models.TextField()),
                ('toughness', models.CharField(max_length=50)),
                ('is_selected', models.BooleanField()),
                ('created_by', models.CharField(max_length=100)),
                ('date_added', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SubjectTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.IntegerField()),
                ('subject_name', models.CharField(max_length=250)),
                ('department_name', models.CharField(max_length=250)),
            ],
        ),
    ]
